In [1]:
print("hello world")

hello world

# Column Transformer

In [42]:
import pandas as pd
import numpy as np

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split

from sklearn.compose import ColumnTransformer

In [4]:
df= pd.read_csv("covid_toy.csv")
df.sample(5)

    age  gender  fever   cough       city has_covid
3    31  Female   98.0    Mild    Kolkata        No
24   13  Female  100.0  Strong    Kolkata        No
74   34  Female  104.0  Strong      Delhi        No
18   64  Female   98.0    Mild  Bangalore       Yes
14   51    Male  104.0    Mild  Bangalore        No

In [8]:
x_train,x_test,y_train,y_test = train_test_split(df.drop(columns=["has_covid"]),df["has_covid"],test_size=0.2,random_state=0)

In [9]:
x_train

    age  gender  fever   cough       city
43   22  Female   99.0    Mild  Bangalore
62   56  Female  104.0  Strong  Bangalore
3    31  Female   98.0    Mild    Kolkata
71   75  Female  104.0  Strong      Delhi
45   72    Male   99.0    Mild  Bangalore
..  ...     ...    ...     ...        ...
96   51  Female  101.0  Strong    Kolkata
67   65    Male   99.0    Mild  Bangalore
64   42    Male  104.0    Mild     Mumbai
47   18  Female  104.0    Mild  Bangalore
44   20    Male  102.0  Strong      Delhi

[80 rows x 5 columns]

#  normal life

In [29]:
si =SimpleImputer()
x_train_fever = si.fit_transform(x_train[["fever"]])

x_test_fever = si.fit_transform(x_test[["fever"]])

x_train_fever.shape

(80, 1)

In [30]:
# odinal encoding ->cough
oe = OrdinalEncoder(categories=[["Mild","Strong"]])

x_train_cough=oe.fit_transform(x_train[["cough"]])

x_test_cough=oe.fit_transform(x_test[["cough"]])

x_train_cough.shape

(80, 1)

In [31]:
# onehot endcoding -> gender and city

ohe=OneHotEncoder(drop="first",sparse_output=False)

x_train_gender_city = ohe.fit_transform(x_train[["gender","city"]])

x_test_gender_city = ohe.fit_transform(x_test[["gender","city"]])

x_train_gender_city.shape

(80, 4)

In [40]:
x_train_age=x_train.drop(columns=["cough", "gender", "city", "fever"]).values
x_test_age=x_test["age"].values

x_train_age.shape

(80, 1)

In [41]:
x_train_transformer =np.concatenate((x_train_age,x_train_cough,x_train_fever,x_train_gender_city),axis=1)

# mentos life

In [44]:
transformer= ColumnTransformer(transformers=[
    ("tnf1",SimpleImputer(),["fever"]),
    ("tnf2",OrdinalEncoder(categories=[["Mild", "Strong"]]),["cough"]),
    ("tnf3",OneHotEncoder(drop="first",sparse_output=False),["gender","city"])
],remainder="passthrough")

In [46]:
transformer.fit_transform(x_train).shape

(80, 7)