In [18]:
import pandas as pd
import seaborn as sns
import numpy as np

In [3]:
iris = sns.load_dataset("iris")

In [4]:
iris

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [5]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
iris["species"]=encoder.fit_transform(iris["species"])

In [6]:
iris

     sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

In [7]:
new_df= iris[iris["species"]!=0][["sepal_length", "sepal_width", "species"]]

In [8]:
new_df

     sepal_length  sepal_width  species
50            7.0          3.2        1
51            6.4          3.2        1
52            6.9          3.1        1
53            5.5          2.3        1
54            6.5          2.8        1
..            ...          ...      ...
145           6.7          3.0        2
146           6.3          2.5        2
147           6.5          3.0        2
148           6.2          3.4        2
149           5.9          3.0        2

[100 rows x 3 columns]

In [20]:
X=new_df.iloc[:,0:2]
y=new_df.iloc[:,-1]

In [13]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

In [14]:
clf1=LogisticRegression()
clf2=DecisionTreeClassifier()
clf3=RandomForestClassifier()

In [17]:
estimators=[("lr",clf1),("dt",clf2),("knn",clf3)]

In [22]:
for estimator in estimators:
    x = cross_val_score(estimator[1],X,y,cv=10,scoring='accuracy')
    print(estimator[0],np.round(np.mean(x),2))

lr 0.75
dt 0.54
knn 0.6

In [23]:
from sklearn.ensemble import VotingClassifier

In [24]:
vc=VotingClassifier(estimators=estimators)
x = cross_val_score(vc,X,y,cv=10,scoring='accuracy')
print(np.round(np.mean(x),2))

0.62

In [25]:
vc=VotingClassifier(estimators=estimators,voting="soft")
x = cross_val_score(vc,X,y,cv=10,scoring='accuracy')
print(np.round(np.mean(x),2))

0.59

In [28]:
vc=VotingClassifier(estimators=estimators,voting="soft",weights=[3,1,2])
x = cross_val_score(vc,X,y,cv=10,scoring='accuracy')
print(np.round(np.mean(x),2))

0.63